### ISSUE TITLE
Lack of interface in SQS queue declaration

### ISSUE THREAD

**Issue by jstachera** [limehome/serverless-express-typescript-sqs#2]
https://github.com/limehome/serverless-express-typescript-sqs/blob/3d397d60786a309a7c74a214c6a4f87fe1f692e9/src/services/queue/sqs-queue.service.ts#L10

`export class SqsQueueService implements QueueService`

**Comment by Teppichseite** [comment]
Thank you very much for the hint. I fixed it.
